// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChromePath() {
    return $Call.ByID(2290076471);
}

/**
 * @param {string} name
 * @param {string} url
 * @param {string} icon
 * @param {string} category
 * @param {string} openMode
 * @returns {$CancellablePromise<$models.Site>}
 */
export function Create(name, url, icon, category, openMode) {
    return $Call.ByID(2359525438, name, url, icon, category, openMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CreateShortcut(id) {
    return $Call.ByID(1275601944, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(1125614645, id);
}

/**
 * @returns {$CancellablePromise<$models.Site[]>}
 */
export function GetAll() {
    return $Call.ByID(3620362053).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} category
 * @returns {$CancellablePromise<$models.Site[]>}
 */
export function GetByCategory(category) {
    return $Call.ByID(2766666915, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetCategories() {
    return $Call.ByID(182115718).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function HasChrome() {
    return $Call.ByID(2300822040);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function IconPath() {
    return $Call.ByID(808195824);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSiteOpen(url) {
    return $Call.ByID(577910017, url);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenInBrowser(url) {
    return $Call.ByID(2546586599, url);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenSite(url) {
    return $Call.ByID(107854225, url);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PopPendingOpen() {
    return $Call.ByID(1129175864);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function Reorder(ids) {
    return $Call.ByID(4036022121, ids);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function SetTitle(title) {
    return $Call.ByID(4197287964, title);
}

/**
 * @param {string} id
 * @param {string} name
 * @param {string} url
 * @param {string} icon
 * @param {string} category
 * @param {string} openMode
 * @returns {$CancellablePromise<void>}
 */
export function Update(id, name, url, icon, category, openMode) {
    return $Call.ByID(4089335683, id, name, url, icon, category, openMode);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function WindowFocus() {
    return $Call.ByID(2004424906);
}

// Private type creation functions
const $$createType0 = $models.Site.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
